Repository sQuiz-2/Core, pull requests merged in 2020-11, with the labels that each got.

#39 Play sounds !
  packages/client/assets/sounds/game-end.mp3
  packages/client/assets/sounds/game-start.mp3
  packages/client/assets/sounds/pop.mp3
  packages/client/assets/sounds/right.mp3
  packages/client/assets/sounds/round-start.mp3
  packages/client/assets/sounds/wrong.mp3
  packages/client/src/components/Game/Quiz.tsx
  packages/client/src/components/Game/index.ts
  packages/client/src/components/GameInput.tsx
  packages/client/src/components/GameMainScreen/GameStatus/Answer.tsx
  packages/client/src/components/GameMainScreen/GameStatus/Question.tsx
  packages/client/src/components/GameMainScreen/GameStatus/Winner.tsx
  packages/client/src/components/GameMainScreen/QuizMainScreen.tsx
  packages/client/src/components/GameSound/QuizSound.tsx
  packages/client/src/components/GameSound/index.ts
  packages/client/src/components/ScoreBoard/index.ts
  packages/client/src/components/Timer/Timer.tsx
  packages/client/src/screens/Room.tsx
  packages/client/src/utils/hooks/socketListener.ts
  packages/client/src/utils/hooks/sound.ts
  packages/client/src/utils/sound.ts
  packages/client/src/utils/sounds.ts
Labels: enhancement

#42 Add oAuth with twitch
  README.md
  packages/backend/.env.example
  packages/backend/app/Controllers/Http/AuthController.ts
  packages/backend/app/Enums/oAuthProviders.ts
  packages/backend/app/Models/OauthToken.ts
  packages/backend/app/Models/User.ts
  packages/backend/app/Utils/oAuth/Twitch.ts
  packages/backend/app/Validators/OAuthValidator.ts
  packages/backend/config/auth.ts
  packages/backend/database/migrations/1604568388632_users.ts
  packages/backend/database/migrations/1604571265431_oauth_tokens.ts
  packages/backend/package.json
  packages/backend/start/routes.ts
  packages/client/App.tsx
  packages/client/package.json
  packages/client/src/components/Header/Profile.tsx
  packages/client/src/components/Home/Profile/NotConnected.tsx
  packages/client/src/components/Home/Profile/ProfileContainer.tsx
  packages/client/src/constant/index.ts
  packages/client/src/constant/oAuthProviders.json
  packages/client/src/global/pseudoState.ts
  packages/client/src/global/userState.ts
  packages/client/src/screens/Home.tsx
  packages/client/src/screens/Room.tsx
  packages/client/src/utils/hooks/oAuthTwitch.ts
  packages/client/src/utils/storage.ts
  yarn.lock
Labels: enhancement

#46 Style the profile card in the home page
  packages/backend/app/Class/RoomPool.ts
  packages/client/App.tsx
  packages/client/assets/images/award.png
  packages/client/assets/images/keyboard.png
  packages/client/assets/images/tick.png
  packages/client/src/components/Card/GameCard/GameCard.tsx
  packages/client/src/components/Card/GameCard/GameCardStyle.tsx
  packages/client/src/components/Card/GameCard/index.ts
  packages/client/src/components/Containers/CenterContainer/CenterContainer.tsx
  packages/client/src/components/Containers/CenterContainer/CenterContainerStyle.tsx
  packages/client/src/components/Containers/CenterContainer/index.ts
  packages/client/src/components/Containers/ResponsiveContainer/ResponsiveContainer.tsx
  packages/client/src/components/Containers/ResponsiveContainer/ResponsiveContainerStyle.tsx
  packages/client/src/components/Containers/ResponsiveContainer/index.ts
  packages/client/src/components/Containers/index.ts
  packages/client/src/components/Footer.tsx
  packages/client/src/components/GameContainer/QuizContainer.tsx
  packages/client/src/components/Header/Header/Header.tsx
  packages/client/src/components/Header/Header/HeaderStyle.tsx
  packages/client/src/components/Header/Header/index.ts
  packages/client/src/components/Header/Logo.tsx
  packages/client/src/components/Header/Logo/Logo.tsx
  packages/client/src/components/Header/Logo/LogoStyle.tsx
  packages/client/src/components/Header/Logo/index.ts
  packages/client/src/components/Header/NavBar/NavBar.tsx
  packages/client/src/components/Header/NavBar/NavBarStyle.tsx
  packages/client/src/components/Header/NavBar/index.ts
  packages/client/src/components/Header/Profile.tsx
  packages/client/src/components/Header/Profile/Profile.tsx
  packages/client/src/components/Header/Profile/ProfileStyle.tsx
  packages/client/src/components/Header/Profile/index.tsx
  packages/client/src/components/Home/Profile/NotConnected.tsx
  packages/client/src/components/Home/Profile/ProfileContainer.tsx
  packages/client/src/components/RoomTitle.tsx
  packages/client/src/constant/oAuthProviders.json
  packages/client/src/navigation/HomeStack.tsx
  packages/client/src/screens/Add.tsx
  packages/client/src/screens/FAQ.tsx
  packages/client/src/screens/Home.tsx
  packages/client/src/screens/Home/Home/Home.tsx
  packages/client/src/screens/Home/Home/index.ts
  packages/client/src/screens/Home/HomeContainer/HomeContainer.tsx
  packages/client/src/screens/Home/HomeContainer/HomeContainerStyle.tsx
  packages/client/src/screens/Home/HomeContainer/index.ts
  packages/client/src/screens/Home/HomeRooms/HomeRooms.tsx
  packages/client/src/screens/Home/HomeRooms/index.ts
  packages/client/src/screens/Home/ProfileConnected/ProfileConnected.tsx
  packages/client/src/screens/Home/ProfileConnected/ProfileConnectedStyle.tsx
  packages/client/src/screens/Home/ProfileConnected/index.ts
  packages/client/src/screens/Home/ProfileContainer/ProfileContainer.tsx
  packages/client/src/screens/Home/ProfileContainer/ProfileContainerStyle.tsx
  packages/client/src/screens/Home/ProfileContainer/index.ts
  packages/client/src/screens/Home/ProfileNotConnected/ProfileNotConnected.tsx
  packages/client/src/screens/Home/ProfileNotConnected/ProfileNotConnectedStyle.tsx
  packages/client/src/screens/Home/ProfileNotConnected/index.ts
  packages/client/src/screens/Home/index.ts
  packages/client/webpack.config.js
  packages/shared/src/enums/oAuthProviders.ts
  packages/shared/src/typings/Room.ts
Labels: enhancement

#55 Listen for scorboard updates in Room root
  packages/client/src/components/GameInput.tsx
  packages/client/src/components/PlayerInfo.tsx
  packages/client/src/screens/Room/GameEnd/Details/Results/GameEndResult.tsx
  packages/client/src/screens/Room/GameEnd/GameEnd/GameEnd.tsx
  packages/client/src/screens/Room/GameEnd/ScoreBoard/Scoreboard/GameEndScoreboard.tsx
  packages/client/src/screens/Room/GameInProgress/GameInPrgress/GameInProgress.tsx
  packages/client/src/screens/Room/GameInProgress/RoomTitle/RoomTitle.tsx
  packages/client/src/screens/Room/GameInProgress/RoomTitle/index.ts
  packages/client/src/screens/Room/GameInProgress/Scoreboard/GameInProgressScoreBoard.tsx
  packages/client/src/screens/Room/Room/Room.tsx
  packages/client/src/utils/hooks/getPlayer.ts
Labels: enhancement

#56 add parsing for answers client/server
  .github/workflows/mandatories.yml
  .github/workflows/publish.yml
  package.json
  packages/backend/app/Class/Player.ts
  packages/backend/app/Class/Quiz.ts
  packages/backend/app/Class/RoomPool.ts
  packages/backend/app/Models/Answer.ts
  packages/backend/package.json
  packages/client/package.json
  packages/client/src/components/GameInput.tsx
  packages/client/src/screens/Home/Home/Home.tsx
  packages/client/src/screens/Home/HomeContainer/HomeContainer.tsx
  packages/client/src/screens/Home/Rooms/HomeRooms.tsx
  packages/client/src/screens/Room/GameInProgress/Answer/GameInProgressAnswer.tsx
  packages/client/src/screens/Room/GameInProgress/GameInPrgress/GameInProgress.tsx
  packages/shared/japaFile.ts
  packages/shared/package.json
  packages/shared/src/functions/Answer.ts
  packages/shared/src/typings/Room.ts
  packages/shared/tests/Answer.spec.ts
  packages/shared/tsconfig.json
  yarn.lock
Labels: enhancement

#57 Allow players to make a mistake in their answer
  packages/backend/app/Class/Quiz.ts
  packages/client/src/components/GameInput.tsx
  packages/shared/src/enums/Game.ts
  packages/shared/src/typings/Room.ts
Labels: enhancement

#58 Score detail
  packages/backend/app/Class/Player.ts
  packages/backend/app/Class/Quiz.ts
  packages/client/assets/images/chest.png
  packages/client/src/screens/Room/GameInProgress/Answer/GameInProgressAnswer.tsx
  packages/client/src/screens/Room/GameInProgress/Answer/index.ts
  packages/client/src/screens/Room/GameInProgress/GameInPrgress/GameInProgress.tsx
  packages/client/src/screens/Room/GameInProgress/GameInput/GameInput.tsx
  packages/client/src/screens/Room/GameInProgress/GameInput/GameInputStyle.tsx
  packages/client/src/screens/Room/GameInProgress/GameInput/index.ts
  packages/client/src/screens/Room/GameInProgress/Question/Question.tsx
  packages/client/src/screens/Room/GameInProgress/Question/QuestionStyle.tsx
  packages/client/src/screens/Room/GameInProgress/Question/index.ts
  packages/client/src/screens/Room/GameInProgress/RoundEnd/Answer/Answer.tsx
  packages/client/src/screens/Room/GameInProgress/RoundEnd/Answer/AnswerStyle.tsx
  packages/client/src/screens/Room/GameInProgress/RoundEnd/Answer/index.ts
  packages/client/src/screens/Room/GameInProgress/RoundEnd/RoundEnd/RoundEnd.tsx
  packages/client/src/screens/Room/GameInProgress/RoundEnd/RoundEnd/RoundEndStyle.tsx
  packages/client/src/screens/Room/GameInProgress/RoundEnd/RoundEnd/index.ts
  packages/client/src/screens/Room/GameInProgress/RoundEnd/ScoreDetail/ScoreDetail.tsx
  packages/client/src/screens/Room/GameInProgress/RoundEnd/ScoreDetail/ScoreDetailStyle.tsx
  packages/client/src/screens/Room/GameInProgress/RoundEnd/ScoreDetail/index.ts
  packages/client/src/screens/Room/GameInProgress/RoundEnd/index.ts
  packages/shared/src/enums/Game.ts
  packages/shared/src/typings/Room.ts
Labels: enhancement

#59 Add medals
  packages/backend/app/Class/Player.ts
  packages/backend/app/Class/Quiz.ts
  packages/backend/app/Class/Room.ts
  packages/client/assets/images/medals/bronze.png
  packages/client/assets/images/medals/gold.png
  packages/client/assets/images/medals/gray.png
  packages/client/assets/images/medals/green.png
  packages/client/assets/images/medals/silver.png
  packages/client/src/components/Card/GameCard/GameCardStyle.tsx
  packages/client/src/components/ScoreBoard/Scoreboard/Scoreboard.tsx
  packages/client/src/components/ScoreBoard/Scoreboard/ScoreboardStyle.tsx
  packages/client/src/components/ScoreBoard/ScoreboardRow/ScoreboardRow.tsx
  packages/client/src/components/ScoreBoard/ScoreboardRow/ScoreboardRowStyle.tsx
  packages/client/src/global/playerInfoState.ts
  packages/client/src/screens/Room/GameEnd/Details/Results/GameEndResult.tsx
  packages/client/src/screens/Room/GameEnd/ScoreBoard/FullScoreboard/GameEndFullScoreboard.tsx
  packages/client/src/screens/Room/GameEnd/ScoreBoard/TopScoreboard/GameEndTopScoreboard.tsx
  packages/client/src/screens/Room/GameInProgress/RoundCounter/RoundCounter.tsx
  packages/client/src/screens/Room/GameInProgress/RoundCounter/RoundCounterStyle.tsx
  packages/client/src/screens/Room/GameInProgress/RoundEnd/RoundEnd/RoundEnd.tsx
  packages/client/src/screens/Room/Room/Room.tsx
  packages/client/src/typings/import-png.d.ts
  packages/client/src/utils/medals.ts
  packages/client/src/utils/players.ts
  packages/shared/src/enums/Game.ts
  packages/shared/src/typings/Room.ts
Labels: enhancement

#61 Use shared as a package
  .github/workflows/pre-prod.yml
  package.json
  packages/backend/Dockerfile
  packages/backend/app/Class/Player.ts
  packages/backend/app/Class/Quiz.ts
  packages/backend/app/Class/Room.ts
  packages/backend/app/Class/RoomPool.ts
  packages/backend/app/Controllers/Http/AuthController.ts
  packages/backend/app/Models/Game.ts
  packages/backend/app/Models/Round.ts
  packages/backend/app/Validators/GameValidator.ts
  packages/backend/app/Validators/OAuthValidator.ts
  packages/backend/app/Validators/RoundValidator.ts
  packages/backend/database/seeders/Default.ts
  packages/backend/package.json
  packages/backend/tsconfig.json
  packages/client/package.json
  packages/client/src/global/playerInfoState.ts
  packages/client/src/screens/Home/Home/Home.tsx
  packages/client/src/screens/Home/HomeContainer/HomeContainer.tsx
  packages/client/src/screens/Home/Infos/News/News/HomeNews.tsx
  packages/client/src/screens/Home/Infos/News/NewsItem/HomeNewsItem.tsx
  packages/client/src/screens/Home/Infos/Profile/ProfileConnected/ProfileConnected.tsx
  packages/client/src/screens/Home/Infos/Profile/ProfileNotConnected/ProfileNotConnected.tsx
  packages/client/src/screens/Home/Rooms/HomeRooms.tsx
  packages/client/src/screens/Room/GameEnd/Details/Questions/GameEndQuestion.tsx
  packages/client/src/screens/Room/GameEnd/GameEnd/GameEnd.tsx
  packages/client/src/screens/Room/GameInProgress/GameInPrgress/GameInProgress.tsx
  packages/client/src/screens/Room/GameInProgress/GameInput/GameInput.tsx
  packages/client/src/screens/Room/GameInProgress/Question/Question.tsx
  packages/client/src/screens/Room/GameInProgress/RoomTitle/RoomTitle.tsx
  packages/client/src/screens/Room/GameInProgress/RoundCounter/RoundCounter.tsx
  packages/client/src/screens/Room/GameInProgress/RoundEnd/Answer/Answer.tsx
  packages/client/src/screens/Room/GameInProgress/RoundEnd/RoundEnd/RoundEnd.tsx
  packages/client/src/screens/Room/GameInProgress/RoundEnd/RoundEnd/RoundEndStyle.tsx
  packages/client/src/screens/Room/GameInProgress/RoundEnd/ScoreDetail/ScoreDetail.tsx
  packages/client/src/screens/Room/Room/Room.tsx
  packages/client/src/utils/hooks/oAuthTwitch.ts
  packages/client/src/utils/medals.ts
  packages/client/src/utils/players.ts
  packages/client/tsconfig.json
  packages/shared/.gitignore
  packages/shared/package.json
  packages/shared/src/enums/Difficulty.ts
  packages/shared/src/enums/index.ts
  packages/shared/src/functions/Answer.ts
  packages/shared/src/functions/index.ts
  packages/shared/src/index.ts
  packages/shared/src/typings/News.ts
  packages/shared/src/typings/index.ts
  packages/shared/tests/Answer.spec.ts
  packages/shared/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: bug

#62 Add more themes
  packages/backend/.adonisrc.json
  packages/backend/app/Class/Quiz.ts
  packages/backend/app/Validators/GameValidator.ts
  packages/backend/app/Validators/RoundValidator.ts
  packages/backend/contracts/validator.ts
  packages/backend/database/seeders/Default.ts
  packages/backend/start/validationRules.ts
  packages/shared/src/enums/Difficulty.ts
Labels: enhancement

#63 Store array of questions
  packages/backend/app/Controllers/Http/RoundsController.ts
  packages/backend/app/Validators/RoundsValidator.ts
  packages/backend/start/routes.ts
Labels: enhancement

#68 fix(shared answer.ts): fix parseAnswer
  packages/shared/src/functions/Answer.ts
  packages/shared/tests/Answer.spec.ts
Labels: enhancement

#70 Improve dev experience
  .gitignore
  README.md
  package.json
  packages/backend/database/seeders/Default.ts
  packages/client/App.tsx
  packages/client/app.json
  packages/client/metro.config.js
  packages/client/package.json
  packages/client/tsconfig.json
  packages/client/webpack.config.js
  packages/shared/package.json
  scripts/init.sh
  scripts/reset.sh
  yarn.lock
Labels: enhancement

#72 Logger
  packages/backend/Dockerfile
  packages/backend/app/Controllers/Http/AuthController.ts
  packages/backend/app/Exceptions/AuthenticationException.ts
  packages/backend/app/Exceptions/Handler.ts
  packages/backend/app/Exceptions/OAuthException.ts
  packages/backend/app/Utils/oAuth/Twitch.ts
  packages/backend/app/Validators/LoginValidator.ts
  packages/backend/package.json
  packages/client/src/utils/hooks/oAuthTwitch.ts
  yarn.lock
Labels: enhancement

#73 Edit cache control
  packages/client/app.json
  packages/client/assets/icon-large.png
  packages/client/assets/icon-medium.png
  packages/client/assets/icon-small.png
  packages/client/assets/icon.png
  packages/client/assets/icons/icon-square.png
  packages/client/assets/icons/icon.png
  packages/client/assets/icons/splash.png
  packages/client/assets/icons/title.png
  packages/client/assets/images/question.png
  packages/client/assets/title.png
  packages/client/src/components/Card/GameCard/GameCard.tsx
  packages/client/src/components/Header/Logo/Logo.tsx
  packages/client/web/_headers
Labels: bug

#74 Create custom scrollbar
  packages/client/web/index.html
Labels: enhancement

#75 Create admin middleware
  packages/backend/app/Exceptions/AdminException.ts
  packages/backend/app/Exceptions/Handler.ts
  packages/backend/app/Middleware/Admin.ts
  packages/backend/app/Models/User.ts
  packages/backend/database/seeders/User.ts
  packages/backend/start/kernel.ts
Labels: enhancement

#76 Only admin can access to admin features
  packages/backend/start/routes.ts
Labels: bug

#77 Refractor server
  packages/backend/app/Class/Player.ts
  packages/backend/app/Class/Quiz.ts
  packages/backend/app/Class/Room.ts
  packages/backend/app/Class/RoomPool.ts
  packages/client/src/screens/Room/GameEnd/Details/Results/GameEndResult.tsx
  packages/client/src/screens/Room/GameInProgress/GameInPrgress/GameInProgress.tsx
  packages/client/src/screens/Room/GameInProgress/Question/Question.tsx
  packages/client/src/screens/Room/GameInProgress/RoundEnd/RoundEnd/RoundEnd.tsx
  packages/shared/src/enums/Game.ts
  packages/shared/src/enums/Room.ts
  packages/shared/src/enums/index.ts
  packages/shared/src/typings/Room.ts
Labels: documentation, enhancement

#78 Room connection
  packages/backend/app/Class/Room.ts
  packages/backend/app/Class/RoomPool.ts
  packages/client/src/screens/Home/Home/Home.tsx
  packages/client/src/screens/Home/HomeContainer/HomeContainer.tsx
  packages/client/src/screens/Home/Rooms/HomeRooms.tsx
  packages/shared/src/enums/Room.ts
  packages/shared/src/typings/Room.ts
  packages/shared/src/typings/index.ts
Labels: enhancement

#79 Room limit connections
  packages/backend/app/Class/Player.ts
  packages/backend/app/Class/Quiz.ts
  packages/backend/app/Class/Room.ts
  packages/client/src/components/SocketError/SocketError.tsx
  packages/client/src/components/SocketError/SocketErrorStyle.tsx
  packages/client/src/components/SocketError/index.ts
  packages/client/src/screens/Room/Room/Room.tsx
  packages/client/src/utils/hooks/socketConnect.ts
  packages/shared/src/enums/Room.ts
  packages/shared/src/enums/index.ts
Labels: enhancement

#80 Room errors
  packages/backend/app/Class/Home.ts
  packages/backend/app/Class/Room.ts
  packages/backend/start/socket.ts
  packages/client/src/components/SocketError/SocketError.tsx
  packages/client/src/screens/Home/Home/Home.tsx
  packages/client/src/utils/hooks/socketConnect.ts
  packages/shared/src/enums/Room.ts
Labels: enhancement
